---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: fortune-deploy
  labels:
    name: fortune-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: fortune-po
  template: 
    metadata:
      name: fortune-po
      labels:
        name: fortune-po
    spec:
      containers:
      - name: fortune
        image: chukmunnlee/fortune:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1 
kind: Service 
metadata:
  name: fortune-svc
  labels:
    name: fortune-svc
spec:
  type: ClusterIP
  selector: 
    name: fortune-po
  ports:
  - port: 3000
    targetPort: 3000

---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata:
  name: fortune-ing 
  labels:
    name: fortune-ing 
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: fortune-144.126.243.25.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: fortune-svc 
            port:
              number: 3000
