---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: Pod 
metadata:
  name: mysql-po
  labels:
    name: mysql-po
spec: 
  volumes:
  - name: data-vol
    persistentVolumeClaim: 
      claimName: mysql-pvc
  containers:
  - name: mysql
    image: mysql:8.0 
    imagePullPolicy: IfNotPresent
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: rootroot
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: data-vol 
      mountPath: /var/lib/mysql